#read in all the csv files

avan_dist=read.csv(file = 'Genomes_fasta/AssemblyStats/a_vanillaeDistribution.csv')
avan_dens=read.csv(file = 'Genomes_fasta/AssemblyStats/a_vanillaeInvDensity.csv')
etal_dist=read.csv(file = 'Genomes_fasta/AssemblyStats/e_talesDistribution.csv')
etal_dens=read.csv(file = 'Genomes_fasta/AssemblyStats/e_talesInvDensity.csv')
hbes_dist=read.csv(file = 'Genomes_fasta/AssemblyStats/h_besckeiDistribution.csv')
hbes_dens=read.csv(file = 'Genomes_fasta/AssemblyStats/h_besckeiInvDensity.csv')
hbur_dist=read.csv(file = 'Genomes_fasta/AssemblyStats/h_burneyiDistribution.csv')
hbur_dens=read.csv(file = 'Genomes_fasta/AssemblyStats/h_burneyiInvDensity.csv')
hcyd_dist=read.csv(file = 'Genomes_fasta/AssemblyStats/h_cydnoDistribution.csv')
hcyd_dens=read.csv(file = 'Genomes_fasta/AssemblyStats/h_cydnoInvDensity.csv')
hdem_dist=read.csv(file = 'Genomes_fasta/AssemblyStats/h_demeterDistribution.csv')
hdem_dens=read.csv(file = 'Genomes_fasta/AssemblyStats/h_demeterInvDensity.csv')
hele_dist=read.csv(file = 'Genomes_fasta/AssemblyStats/h_elevatusDistribution.csv')
hele_dens=read.csv(file = 'Genomes_fasta/AssemblyStats/h_elevatusInvDensity.csv')
hehi_dist=read.csv(file = 'Genomes_fasta/AssemblyStats/h_erato_himera_hybridDistribution.csv')
hehi_dens=read.csv(file = 'Genomes_fasta/AssemblyStats/h_erato_himera_hybridInvDensity.csv')
hera_dist=read.csv(file = 'Genomes_fasta/AssemblyStats/h_eratoDistribution.csv')
hera_dens=read.csv(file = 'Genomes_fasta/AssemblyStats/h_eratoInvDensity.csv')
hhec_dist=read.csv(file = 'Genomes_fasta/AssemblyStats/h_hecaleDistribution.csv')
hhec_dens=read.csv(file = 'Genomes_fasta/AssemblyStats/h_hecaleInvDensity.csv')
hhim_dist=read.csv(file = 'Genomes_fasta/AssemblyStats/h_himeraDistribution.csv')
hhim_dens=read.csv(file = 'Genomes_fasta/AssemblyStats/h_himeraInvDensity.csv')
hmel_dist=read.csv(file = 'Genomes_fasta/AssemblyStats/h_melpomeneDistribution.csv')
hmel_dens=read.csv(file = 'Genomes_fasta/AssemblyStats/h_melpomeneInvDensity.csv')
hnum_dist=read.csv(file = 'Genomes_fasta/AssemblyStats/h_numataDistribution.csv')
hnum_dens=read.csv(file = 'Genomes_fasta/AssemblyStats/h_numataInvDensity.csv')
hpar_dist=read.csv(file = 'Genomes_fasta/AssemblyStats/h_pardalinusDistribution.csv')
hpar_dens=read.csv(file = 'Genomes_fasta/AssemblyStats/h_pardalinusInvDensity.csv')
htel_dist=read.csv(file = 'Genomes_fasta/AssemblyStats/h_telesipheDistribution.csv')
htel_dens=read.csv(file = 'Genomes_fasta/AssemblyStats/h_telesipheInvDensity.csv')
htim_dist=read.csv(file = 'Genomes_fasta/AssemblyStats/h_timaretaDistribution.csv')
htim_dens=read.csv(file = 'Genomes_fasta/AssemblyStats/h_timaretaInvDensity.csv')
ldor_dist=read.csv(file = 'Genomes_fasta/AssemblyStats/l_dorisDistribution.csv')
ldor_dens=read.csv(file = 'Genomes_fasta/AssemblyStats/l_dorisInvDensity.csv')
naoe_dist=read.csv(file = 'Genomes_fasta/AssemblyStats/n_aoedeDistribution.csv')
naoe_dens=read.csv(file = 'Genomes_fasta/AssemblyStats/n_aoedeInvDensity.csv')

hmelClip2_dist=read.csv(file = 'Genomes_fasta/AssemblyStats/h_melpomene_clipped.fastaDistribution.csv')
hmelClip2_dens=read.csv(file = 'Genomes_fasta/AssemblyStats/h_melpomene_clipped.fastaInvDensity.csv')
hmelClip_dist=read.csv(file = 'Genomes_fasta/AssemblyStats/h_melpomene_clippedDistribution.csv')
hmelClip_dens=read.csv(file = 'Genomes_fasta/AssemblyStats/h_melpomene_clippedInvDensity.csv')
#################
#graph 'em!

par(mfrow=c(1,2))

plotEm <- function(x,y,lab){
  hist(x$length, ylab=lab, xlab="Length", main="Distribution", xlim=c(0,30000), breaks=300)
  plot(y$length, y$pctScaffolds, type="l", ylim=c(0,1), main="Inverse Density", ylab="Percent of scaffolds", xlab="Length")
  points(y$length, y$pctScaffolds)
}

plotEm(x=avan_dist, y=avan_dens, lab="A_vanillae")
plotEm(x=etal_dist, y=etal_dens, lab="E_tales")
plotEm(x=hbes_dist, y=hbes_dens, lab="H_besckei")
plotEm(x=hbur_dist, y=hbur_dens, lab="H_burneyi")
plotEm(x=hcyd_dist, y=hcyd_dens, lab="H_cydno")
plotEm(x=hdem_dist, y=hdem_dens, lab="H_demeter")
plotEm(x=hehi_dist, y=hehi_dens, lab="H_erato_H_himera Hybrid")
plotEm(x=hera_dist, y=hera_dens, lab="H_erato")
plotEm(x=hele_dist, y=hele_dens, lab="H_elevatus")
plotEm(x=hhec_dist, y=hhec_dens, lab="H_hecale")
plotEm(x=hhim_dist, y=hhim_dens, lab="H_himera")
plotEm(x=hmel_dist, y=hmel_dens, lab="H_melpomene")
plotEm(x=hnum_dist, y=hnum_dens, lab="H_numata")
plotEm(x=hpar_dist, y=hpar_dens, lab="H_pardalinus")
plotEm(x=htel_dist, y=htel_dens, lab="H_telesiphe")
plotEm(x=htim_dist, y=htim_dens, lab="H_timareta")
plotEm(x=ldor_dist, y=ldor_dens, lab="L_doris")
plotEm(x=naoe_dist, y=naoe_dens, lab="N_aoede")

